<script>
export default {
  props: {
    product: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      animation: false,
    };
  },
};
</script>

<template>
  <div class="cursor-pointer w-[240px]  h-[127px]" @mouseover="animation = true" @mouseleave="animation = false">
    <div class="flex py-5 px-5">
     <div class="w-[100px]">
       <h1 class="font-semibold text-sm text-wrap">{{ product.title }}</h1>
       <h1 class="font-semibold text-sm text-gray-500">USD {{ product.price }}</h1>
     </div>
     <router-link :to="`single-page/${this.product.id}`">
      <img
      class="w-[72px] h-[72px] rounded-lg mt-5 ml-3"
      :class="{ 'wobble-hor-bottom': animation === true }"
      :src="product.images[0]"
      alt="product image"
    />
    </router-link>
    </div>
  </div>
</template>

<style scoped>
.wobble-hor-bottom {
  -webkit-animation: wobble-hor-bottom 0.8s infinite both;
  animation: wobble-hor-bottom 0.8s infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-2-29 9:53:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
    transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
    transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
    transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
    transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
    transform: translateX(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
    transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
    transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
    transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
    transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
    transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
    transform: translateX(-6px) rotate(-1.2deg);
  }
}
</style>
